In [1]:
import pandas as pd 
from tqdm import tqdm
import os
import torch
import numpy as np
from torch.utils.data import Dataset
from torchvision import datasets, models, transforms
import PIL
from torch.utils.data import DataLoader
import torch.nn as nn
import torch.optim as optim
from sklearn.metrics import classification_report

In [2]:
folder_path = 'nozzle_data'

In [3]:
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self, csv_path, images_folder, transform = None):
        self.df = pd.read_csv(csv_path)
        self.images_folder = images_folder
        self.transform = transform

    def __len__(self):
        return len(self.df)
    def __getitem__(self, index):
        image_path = self.df.loc[index]['img_path']
        label = self.df.iloc[index][-1].astype(float)
        image = PIL.Image.open(os.path.join(self.images_folder, image_path))
        if self.transform is not None:
            image = self.transform(image)
        return image, label

In [4]:
images_folder = os.path.join(folder_path, 'images')
train_csv = os.path.join(folder_path,'train.csv')

transform = transforms.Compose([
                    transforms.AutoAugment(),
                    transforms.ToTensor(),
                    transforms.Resize(size=(480, 640), antialias=True),
                    transforms.RandomHorizontalFlip(),
                    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])])
dataset = CustomDataset(train_csv, images_folder,transform)
trainDataset,testDataset=torch.utils.data.random_split(dataset, [0.9,0.1],)

In [5]:
import gc
gc.collect()
torch.cuda.empty_cache()

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [8]:


model = models.resnet18(weights='ResNet18_Weights.IMAGENET1K_V1')
model_features = model.fc.in_features
model.fc = nn.Sequential(
    nn.Linear(model_features, 256),
    nn.Linear(256, 128),
    nn.Linear(128, 64),
    nn.Linear(64, 8),
    nn.Linear(8, 2)
)
model.to(device)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [9]:
train_loader =  DataLoader(trainDataset, batch_size=32, shuffle=True)
test_loader =  DataLoader(testDataset, batch_size=32, shuffle=False)
model.train(mode=True)
size = len(trainDataset)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5, weight_decay=1e-4, momentum=0.9)

epochs = 10

In [26]:
model.train(mode=True)
for epoch in range(epochs):
    running_loss = 0.0
    total = 0
    correct = 0
    progress_bar = tqdm(range(size//32), position=0, desc='[TRAINING]. ')
    train_loss_history = []
    for i, data in enumerate(train_loader):
        inputs, labels = data
        labels = labels.type(torch.LongTensor)
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        labels = labels  
        correct += (predicted == labels).sum().item()
        accuracy = correct / total * 100
        progress_bar.set_description(f"EPOCH [{epoch+1}/{epochs}]")
        progress_bar.set_postfix(loss=loss, acc=(100*correct/total))
        progress_bar.update()
        
    print(f'epoch: {epoch + 1} loss: {running_loss / len(train_loader):.3f}, accuracy: {accuracy:.2f}%')
    running_loss = 0.0
    total = 0
    correct = 0

print('Finished Training')

torch.save(model.state_dict(), 'model_parameters.pth')

EPOCH [2/10]:  19%|█▉        | 430/2279 [07:56<34:08,  1.11s/it, acc=10.4, loss=tensor(0.6746, device='cuda:0', grad_fn=<NllLossBackward0>)]
C:\Users\aalqa\AppData\Local\Temp\ipykernel_39512\1188216517.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  label = self.df.iloc[index][-1].astype(float)
EPOCH [1/10]: : 2280it [41:33,  1.12s/it, acc=56.4, loss=tensor(0.6722, device='cuda:0', grad_fn=<NllLossBackward0>)]                        

epoch: 1 loss: 0.671, accuracy: 56.42%


EPOCH [1/10]: : 2280it [41:33,  1.09s/it, acc=56.4, loss=tensor(0.6722, device='cuda:0', grad_fn=<NllLossBackward0>)]
EPOCH [2/10]: : 2280it [41:32,  1.07s/it, acc=59.6, loss=tensor(0.7022, device='cuda:0', grad_fn=<NllLossBackward0>)]                        

epoch: 2 loss: 0.666, accuracy: 59.59%


EPOCH [2/10]: : 2280it [41:32,  1.09s/it, acc=59.6, loss=tensor(0.7022, device='cuda:0', grad_fn=<NllLossBackward0>)]
EPOCH [3/10]: : 2280it [40:57,  1.05it/s, acc=63.1, loss=tensor(0.6424, device='cuda:0', grad_fn=<NllLossBackward0>)]                        

epoch: 3 loss: 0.658, accuracy: 63.09%


EPOCH [3/10]: : 2280it [40:57,  1.08s/it, acc=63.1, loss=tensor(0.6424, device='cuda:0', grad_fn=<NllLossBackward0>)]
EPOCH [4/10]: : 2280it [40:56,  1.09s/it, acc=66.6, loss=tensor(0.6316, device='cuda:0', grad_fn=<NllLossBackward0>)]                        

epoch: 4 loss: 0.648, accuracy: 66.64%


EPOCH [4/10]: : 2280it [40:56,  1.08s/it, acc=66.6, loss=tensor(0.6316, device='cuda:0', grad_fn=<NllLossBackward0>)]
EPOCH [5/10]: : 2280it [41:07,  1.10s/it, acc=69.4, loss=tensor(0.5824, device='cuda:0', grad_fn=<NllLossBackward0>)]                        

epoch: 5 loss: 0.634, accuracy: 69.43%


EPOCH [5/10]: : 2280it [41:07,  1.08s/it, acc=69.4, loss=tensor(0.5824, device='cuda:0', grad_fn=<NllLossBackward0>)]
EPOCH [6/10]: : 2280it [41:35,  1.12s/it, acc=72.3, loss=tensor(0.6024, device='cuda:0', grad_fn=<NllLossBackward0>)]                        

epoch: 6 loss: 0.613, accuracy: 72.26%


EPOCH [6/10]: : 2280it [41:35,  1.09s/it, acc=72.3, loss=tensor(0.6024, device='cuda:0', grad_fn=<NllLossBackward0>)]
EPOCH [7/10]: : 2280it [41:54,  1.13s/it, acc=74.1, loss=tensor(0.5518, device='cuda:0', grad_fn=<NllLossBackward0>)]                        

epoch: 7 loss: 0.582, accuracy: 74.13%


EPOCH [7/10]: : 2280it [41:54,  1.10s/it, acc=74.1, loss=tensor(0.5518, device='cuda:0', grad_fn=<NllLossBackward0>)]
EPOCH [8/10]: : 2280it [42:57,  1.07s/it, acc=76.7, loss=tensor(0.4711, device='cuda:0', grad_fn=<NllLossBackward0>)]                        

epoch: 8 loss: 0.539, accuracy: 76.72%


EPOCH [8/10]: : 2280it [42:57,  1.13s/it, acc=76.7, loss=tensor(0.4711, device='cuda:0', grad_fn=<NllLossBackward0>)]
EPOCH [9/10]: : 2280it [42:57,  1.11s/it, acc=79.4, loss=tensor(0.4570, device='cuda:0', grad_fn=<NllLossBackward0>)]                        

epoch: 9 loss: 0.483, accuracy: 79.43%


EPOCH [9/10]: : 2280it [42:57,  1.13s/it, acc=79.4, loss=tensor(0.4570, device='cuda:0', grad_fn=<NllLossBackward0>)]
EPOCH [10/10]: : 2280it [42:37,  1.01s/it, acc=82.8, loss=tensor(0.3390, device='cuda:0', grad_fn=<NllLossBackward0>)]                        

epoch: 10 loss: 0.420, accuracy: 82.81%
Finished Training


In [27]:
model.eval()

correct = 0
total = 0
all_labels = []
all_preds = []
with torch.no_grad():
    for inputs, labels in test_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, predicted = torch.max(outputs, 1)
        real = labels
        print(predicted)
        total += labels.size(0)
        all_labels.extend(real.cpu().numpy())
        all_preds.extend(predicted.cpu().numpy())
        correct += (predicted == real).sum().item()

        accuracy = correct / total * 100
        print(f'Test Accuracy: {accuracy:.2f}%') 

C:\Users\aalqa\AppData\Local\Temp\ipykernel_39512\1188216517.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  label = self.df.iloc[index][-1].astype(float)


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
        1, 0, 1, 1, 1, 0, 0, 1], device='cuda:0')
Test Accuracy: 71.88%
tensor([1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
Test Accuracy: 78.12%
tensor([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
        1, 0, 0, 1, 0, 0, 1, 0], device='cuda:0')
Test Accuracy: 76.04%
tensor([1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
        0, 1, 1, 1, 0, 1, 0, 1], device='cuda:0')
Test Accuracy: 78.12%
tensor([1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
        0, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
Test Accuracy: 78.12%
tensor([0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
        0, 0, 0, 1, 0, 0, 1, 0], device='cuda:0')
Test Accuracy: 80.21%
tensor([1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
        